### ISSUE TITLE
Some confusion

### ISSUE THREAD

**Issue by xixivvv** [PatrickZH/DeepCore#1]
Could you please provide the environmental requirements of the code requirements?
Also, have FL and GC methods not been added yet?
Thank you very much

**Comment by Chengcheng-Guo** [comment]
We have just uploaded [requirements.txt](https://github.com/PatrickZH/DeepCore/blob/main/requirements.txt), check it out for the environmental requirements.

GC and FL are actually abbreviations of two submodular fucntions Graph Cut and Facility Location. You can use argument ```--selection Submodular --submodular GraphCut``` and ```--selection Submodular --submodular FacilityLocation``` to test these two methods.
