### ISSUE TITLE
Introducing a new baseline from a NeurIPS 2022 Workshop

### ISSUE THREAD

**Issue by dongmean** [PatrickZH/DeepCore#5]
Thank you very much for providing a good & well-reproducible github repository :)

I want to introduce a new data subset selection baseline, which will be published in NeurIPS 2022 [HITY ](https://hity-workshop.github.io/NeurIPS2022/)Workshop. 

`Paper & Code for the new baseline`
- Active Learning is a Strong Baseline for Data Subset Selection [[pdf](https://openreview.net/forum?id=PAgpyQ5rGS)] [[code](https://github.com/dongmean/AL_vs_SubsetSelection/blob/main/README.md)]

Most code and implementations are based on this DeepCore repository.
Thanks again for your great work!

Also, if you want, you can introduce or mention our work in your repository :)
Thanks.

**Comment by PatrickZH** [comment]
It looks interesting. Thanks for bringining it to my attention! I will include it in this repo.
